# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
      - main
      - next

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  RUNNER_TOOL_CACHE: /toolcache
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore --locked-mode
    - name: Build
      run: dotnet build --configuration RELEASE --nologo --no-restore --property:PackageBasePath=./dist/nuget --property:IsGitHub=true
    - name: Publish
      run: dotnet nuget push --api-key "${{ secrets.nuget_token }}" --source https://api.nuget.org/v3/index.json ./dist/nuget/*.nupkg

